version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3335:3335
    environment:
      - DATABASE_URL=
      - SQS_EDITAR_STATUS_PEDIDO_QUEUE=
      - AWS_REGION=
      - AWS_ACCESS_KEY_ID_B64=
      - AWS_SECRET_ACCESS_KEY_B64=